### ISSUE TITLE
Release v0.8.0?

### ISSUE THREAD

**Issue by AldenPeterson** [jstockwin/py-pdf-parser#200]
Is it possible to get a release of the current master?

The reason I am asking is that the version of py-yaml pinned has a security vulnerability - https://snyk.io/vuln/SNYK-PYTHON-PYYAML-590151

The fix is already in master though: https://github.com/jstockwin/py-pdf-parser/blob/master/setup.py#L32

Because of this we're unable to use py-pdf-parser as it is failing our automatic security checks because of the above vulnerability.

Happy to put up a PR for a release too if that's what you'd prefer :)

**Comment by AldenPeterson** [comment]
https://github.com/jstockwin/py-pdf-parser/pull/201

**Comment by jstockwin** [comment]
@AldenPeterson Thanks for this!
I've just approved CI on your PR (which is a new GitHub security thing, I think). Once that's done I'll merge and do the new GitHub release!

**Comment by jstockwin** [comment]
@AldenPeterson All done - the release is now available on PyPI: https://pypi.org/project/py-pdf-parser/0.8.0/

Thanks again!
