### ISSUE TITLE
Py PDF Parser tests are distributed in PyPi wheels

### ISSUE THREAD

**Issue by aiden2480** [jstockwin/py-pdf-parser#383]
**Bug Report**

Py PDF Parser tests are included in the wheel file uploaded to PyPi and are distributed to users when they download. Downloading and inspecting [py-pdf-parser-0.12.0.tar.gz](https://files.pythonhosted.org/packages/9d/87/83f7d9b9571995887dfdc8b3f0d29db6f956c4f6eef30584f70705803540/py-pdf-parser-0.12.0.tar.gz) will reveal this.

This conflicts with imports as this package can actually be imported from any python file. The contents of the file show it belongs to PyPDFParser
```py
>>> from tests import test_filtering
>>> dir(test_filtering)
['BaseTestCase', 'BoundingBox', 'ElementList', 'ElementOutOfRangeError', 'FakePDFMinerTextElement', 'MultipleElementsFoundError', 'NoElementFoundError', 'PDFDocument', 'PDFElement', 'Page', 'TestFiltering', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'call', 'create_pdf_document', 'patch', 're']
```

Folder view of `tests` in `site-packages`

![image](https://github.com/jstockwin/py-pdf-parser/assets/19619206/6c240c31-ef12-4d3b-8d70-60a86f1545a9)

**Comment by jstockwin** [comment]
Agree we should exclude this from the built package. The sample PDFs should definitely not be included - that's a good amount of file size that's not needed.
